name: malaysia_living_cost
description: A Flutter app for Malaysia living cost and savings calculation.

publish_to: "none" 

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Needed packages
  fl_chart: ^0.69.0
  url_launcher: ^6.3.0
  pdf: ^3.10.8
  printing: ^5.12.0
  excel: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
